version: '3.3'
services:
  app:
    build:
      context: ./
    restart: on-failure
    ports:
      - 443:${port}
    volumes:
      # Since we have multiple config files, we cannot use secrets
      - ${assets}:/usr/src/absolutelyapricot.dev/assets:rw
      - ${config}:/usr/src/absolutelyapricot.dev/config:r