name: Scan Dependencies

on:
  push:
  workflow_dispatch:

concurrency:
  group: analysis

jobs:
  audit:
    runs-on: linux

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: 'npm'

    - run: npm ci
    # Fail on moderate audit failures
    - run: npm audit --audit-level=moderate